services:
  - redis-server
language: ruby
rvm:
  - 2.1.1
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec -c spec -fd
  - bundle exec cucumber features